modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/PlayWithMaulana/lotmmi/issues"

[[mods]]
modId="lotmmi"
version="1.0.0"
displayName="LOTM Mystical Items"
authors="Maul"
description="An addon for LotMCraft that adds mystical items from Lord of the Mysteries"

[[dependencies.lotmmi]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lotmmi]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lotmmi]]
    modId="lotmcraft"
    type="required"
    versionRange="[1.0.0,)"
    ordering="AFTER"
    side="BOTH"
